# Nixpacks configuration for Railway
# Simplified config focusing on core dependencies

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "python311"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:clear",
    "php artisan view:clear"
]

[phases.deploy]
cmd = "chmod +x start.sh && ./start.sh"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NODE_VERSION = "18"
